title = "Aimee's Travel Blog"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  name = "Aimee"
  favicon = ""
  description = "Aimee's Travel blog, follow me on my travels and adventures."
  facebook = ""
  twitter = "https://twitter.com/aimeetacchi"
  instagram = "https://instagram.com/darkxangel84"
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/hero.jpg"
  recent_posts_number = 2
